[package]
name = "abac"
version = "0.1.0"
authors = ["Aleksey Ivanov <ialexxei@gmail.com>"]

[dependencies]
diesel = { git = "https://github.com/diesel-rs/diesel", features = ["postgres", "uuid"] }
uuid = { version = "0.6.5", features = ["v4"] }
